testing status
Signed-off-by: Doug Davis <duglin@gmail.com>

diff --git a/.github/workflows/rebuild-site.yml b/.github/workflows/rebuild-site.yml
--- a/.github/workflows/rebuild-site.yml
+++ b/.github/workflows/rebuild-site.yml
@@ -7,6 +7,8 @@ on:
   push:
     branches:
       - main
+    paths-ignore:
+      - 'site/xreg/**'
 
 concurrency:
   group: regen-site
@@ -42,7 +44,7 @@ jobs:
         id: git_check
         run: |
           git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@://github.com"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
           git add .
 
@@ -81,3 +83,16 @@ jobs:
         # Only run if something changed
         if: steps.git_check.outputs.skip != 'true'
         uses: actions/deploy-pages@v4
+
+  status:
+    name: regen-status
+    runs-on: ubuntu-latest
+    needs: [update-repo]
+    if: ${{ always() }}
+    steps:
+      - run: |
+          if [ "${{ needs.update-repo.result }}" != "success" ]; then
+            echo "regen failed"
+            exit 1
+          fi
+          echo "regen succeeded"
